rnd00/kinzame

Gemfile, Gemfile.lock, README.md, app/models/contract.rb, app/models/loan.rb, app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20200224091630_create_loans.rb, db/migrate/20200224092450_devise_create_users.rb, db/migrate/20200224092830_create_contracts.rb, db/migrate/20200224093739_add_columns_to_users.rb, db/migrate/20200224094651_add_default_value_to_user.rb, db/migrate/20200224100535_add_references_to_loans.rb, db/migrate/20200224102338_add_default_and_references_to_contracts.rb, db/schema.rb, test/models/contract_test.rb, test/models/loan_test.rb, test/models/user_test.rb
This will implements:
- [readme updates](https://github.com/rnd00/kinzame/pull/1)
- [database creation / validations](https://github.com/rnd00/kinzame/pull/3)
**edit this as you go**
=> 2/24 Updates

Gemfile, Gemfile.lock, app/models/user.rb, db/seeds.rb
Seeding issues resolved
User model associations created
=> Develop create seeds

config/routes.rb, test/controllers/pages_controller_test.rb
=> made pages controller

app/controllers/loans_controller.rb, test/controllers/loans_controller_test.rb
=> loans controller created

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_landing-page.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_fonts.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_flashes.html.erb
Basic styling completed, will need to update with links
=> Develop create landing page

config/puma.rb
- it crashes out heroku, so i commented it out
=> removing pidfile config

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/contracts_controller.rb, app/controllers/loans_controller.rb, app/controllers/pages_controller.rb, app/models/contract.rb, app/models/user.rb, app/policies/application_policy.rb, app/policies/contract_policy.rb, app/policies/loan_policy.rb, app/views/shared/_navbar.html.erb, config/routes.rb, test/policies/contract_policy_test.rb, test/policies/loan_policy_test.rb
Methods added to Contract and Loan Models and Controllers
=> Devlop add pundit

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
Basic footer completed, links to github profiles added
=> Develop create footer

app/policies/contract_policy.rb, app/policies/loan_policy.rb, db/migrate/20200225071059_add_admin_to_users.rb, db/schema.rb, db/seeds.rb
=> added admin users

app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb
=> added devise routes

db/seeds.rb
Randomized boolean values
Both lenders and borrowers produced
=> made the seed more robust

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/policies/loan_policy.rb, app/views/shared/_navbar.html.erb
Created 3 main styles of buttons
=> added styles for main, reject and approve buttons

app/controllers/users_controller.rb, app/models/loan.rb, app/models/user.rb, app/policies/contract_policy.rb, app/policies/user_policy.rb, app/views/users/contracts_index.html.erb, config/routes.rb, test/policies/user_policy_test.rb
Just the route to the dashboard to display all contracts that belong to the lender.
=> created lender contract index route

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_loan-form.scss, app/views/loans/_form.html.erb, app/views/loans/new.html.erb
Completed initial styling of the new loan form
=> Develop style new loan

app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
- fixing navbar to the top
- getting the footer all the way down and give it a `6.25rem` margin (top)
=> updating navbar and footer

app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_loan-card.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/contracts_controller.rb, app/views/users/_loan-card.html.erb, app/views/users/contracts_index.html.erb, config/routes.rb
styled loan cards simply and fixed routes so it works
=> Develop style loan card

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_loan-card.scss, app/assets/stylesheets/components/_sidebar.scss, app/views/users/_loan-card.html.erb, app/views/users/_sidebar.html.erb
done the basics to dispaly loan and button
=> updated new loan button and the loan cards

app/views/loans/show.html.erb, app/views/shared/_navbar.html.erb, app/views/users/_loan-card.html.erb
Created basic single loan display
=> added very basic design for showpage

config/routes.rb, db/seeds.rb
Seeds will now run without dropping the db.
=> fixed db seed bug

.gitignore, Gemfile, Gemfile.lock
.env added
cloudinary gem added 
need to work on implementing that in backend
=> Develop create cloudinary

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_sidebar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss
Improved the styling of the side bar to go with the styling of the cars
=> Develop style sidebar

app/assets/stylesheets/components/_loan-card.scss, app/controllers/contracts_controller.rb, app/views/users/_loan-card.html.erb, app/views/users/dashboard.html.erb
Bsic version is working to show more information
=> Develop create click to expand

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_login-page.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/users/dashboard.html.erb
- replicating how github did their login/signup page
=> styling for login and signup

app/assets/stylesheets/components/_loan-card.scss, app/assets/stylesheets/components/_sidebar.scss, app/policies/contract_policy.rb, app/views/users/_active-loan.html.erb, app/views/users/_all-loan-table.html.erb, app/views/users/_loan-header-pending.html.erb, app/views/users/_loan-header.html.erb, app/views/users/_pending-loan-table.html.erb, app/views/users/_sidebar.html.erb, app/views/users/dashboard.html.erb
Finished the basic version for both borrower and lender
=> Develop create borrower dash

app/controllers/contracts_controller.rb, app/models/contract.rb, app/models/user.rb, app/views/contracts/_form.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20200227071926_create_active_storage_tables.active_storage.rb, db/schema.rb
Cloudinary install done, showing in the views
=> Develop update cloudinary

app/assets/stylesheets/components/_loan-card.scss, app/views/users/_active-loan.html.erb, app/views/users/_all-loan-table.html.erb, app/views/users/_loan-approval-buttons.html.erb, app/views/users/_loan-card.html.erb, app/views/users/_loan-dropdown.html.erb, app/views/users/_loan-paid-buttons.html.erb, app/views/users/_payment-confirm-loan-table.html.erb, app/views/users/_pending-loan-table.html.erb, app/views/users/dashboard.html.erb
added working drop downs for all loan cards, yet to be properly styled
=> Develop style loan card info

app/assets/stylesheets/components/_footer.scss, app/javascript/packs/application.js, app/views/shared/_footer.html.erb
Made the footer nicer with better colour and added popover for our pics
=> Develop style footer

app/assets/stylesheets/components/_sidebar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/views/users/_loan-dropdown.html.erb
=> removed test text and changed background colour to off white

app/assets/stylesheets/components/_loan-card.scss, app/views/users/_active-loan.html.erb, app/views/users/_all-loan-table.html.erb, app/views/users/_loan-card.html.erb, app/views/users/dashboard.html.erb
Several fixes to borrower dispaly
=> Develop fix displaypendingonborrower

app/controllers/contracts_controller.rb, app/controllers/users_controller.rb, app/policies/user_policy.rb, app/views/users/_charge_form.html.erb, config/routes.rb
Fix adding money to wallet
need to fix subtract
=> Fix add money to wallet

app/assets/stylesheets/components/_loan-card.scss, app/views/users/_loan-dropdown.html.erb
now working with some style fixes
=> Develop fix approval button for borrower

app/assets/stylesheets/components/_sidebar.scss, app/controllers/contracts_controller.rb, app/views/users/_active-loan.html.erb, app/views/users/_all-loan-table.html.erb, app/views/users/_loan-card.html.erb, app/views/users/_loan-dropdown.html.erb, app/views/users/_loan-repay-buttons.html.erb, app/views/users/_sidebar.html.erb
made several changes to display for sidebar and the loan cards
=> Develop fix modify sidebar

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> removed the avatar and changed with burger

app/views/shared/_navbar.html.erb, app/views/users/_loan-dropdown.html.erb
=> fixed the view for lender, need to test with borrower

db/seeds.rb
working for presentation with 2 loans for brian seeded
=> fixed seeds for presentation

app/views/users/_loan-dropdown.html.erb
=> fixed button on drop down

app/views/users/_loan-dropdown.html.erb, app/views/users/dashboard.html.erb
=> Develop fix morepresentationfiex

app/assets/stylesheets/components/_loan-card.scss, app/views/users/_all-loan-table.html.erb, app/views/users/_charge_form.html.erb, app/views/users/_sidebar.html.erb, app/views/users/dashboard.html.erb
=> Develop fix styling

app/assets/stylesheets/components/_loan-card.scss, app/views/users/_all-loan-table.html.erb, db/seeds.rb
=> Develop fix presentationstuff
